### ISSUE TITLE
May I know when will the SPDocVQA be integrated into HF? Thanks!

### ISSUE THREAD

**Issue by MorrisXu-Driving** [rubenpt91/PFL-DocVQA-Competition#13]

**Comment by Solosneros** [comment]
Hi @MorrisXu-Driving,

we try to streamline the questions regarding the competition and you will receive a quicker answer by email:

For any question about this challenge, please contact [info_pfl@cvc.uab.cat](mailto:info_pfl@cvc.uab.cat).

Best,

**Comment by Solosneros** [comment]
I close this and feel free to open if needed! :)
